In [12]:
from data import *
from network import *

In [5]:
train = load_data()

In [6]:
X,y = train

In [7]:
X.shape

(60000, 784)

In [17]:
y.shape
print(y)

[8 7 0 ... 0 4 9]


In [9]:
onehot_encode(y)

a


array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [14]:
Network((batch_size=1, epochs=100, k_folds=5, lr=0.001, normalization=data.min_max_normalize, patience=100), sigmoid, multiclass_cross_entropy, 60000)

SyntaxError: invalid syntax (3771253473.py, line 1)

In [10]:
sigmoid(3)

0.9525741268224334

In [15]:
generate_k_fold_set(train)

<generator object generate_k_fold_set at 0x11f258190>

In [77]:
train[1]

array([8, 7, 0, ..., 0, 4, 9], dtype=uint8)

In [78]:
X,y = train

In [88]:
X.shape

(60000, 784)

In [84]:
z = z_score_normalize(X)

In [86]:
print(z)

None


In [93]:
min_max_normalize(X)

In [98]:
print(onehot_encode(y))

None


In [113]:
for i in range(0, 5, 2):
    print(i)

0
2
4


In [44]:
b = np.array([1,2,3])

In [22]:
np.resize (b, (2,3))

array([[1, 2, 1],
       [2, 1, 2]])

In [37]:
a.shape[1]

3

In [45]:
b = np.expand_dims(b, axis=1)

In [46]:
c = np.repeat(b, a.shape[0], axis=1).T

In [49]:
c

array([[1, 2, 3],
       [1, 2, 3]])

In [48]:
a/c

array([[1.        , 2.5       , 2.        ],
       [1.        , 1.5       , 1.33333333]])

In [114]:
a

array([[1, 5, 6],
       [1, 3, 4]])

In [52]:
np.min(a)

1

In [69]:
values = [1, 0, 2, 1, 3, 2, 1, 1]
n_values = np.max(values) + 1
en = np.eye(n_values)[values]

In [70]:
np.argmax(en, axis=1)

array([1, 0, 2, 1, 3, 2, 1, 1])

In [71]:
a

array([[1, 5, 6],
       [1, 3, 4]])

In [74]:
np.hstack([a, np.ones((2,1))])

array([[1., 5., 6., 1.],
       [1., 3., 4., 1.]])

In [109]:
1//3

0

In [115]:
a

array([[1, 5, 6],
       [1, 3, 4]])

In [116]:
c

array([[1, 2, 3],
       [1, 2, 3]])

In [119]:
for i,j in zip(a,c):
    print(i+j)

[2 7 9]
[2 5 7]


In [127]:
out = np.array([[0.6, 0.2, 0.2],
               [0.1, 0.7, 0.2]])

In [137]:
label = np.array([[1,0,0],
                 [1,0,0]])

In [133]:
np.sum((out > 0.5) == label)

6

In [128]:
np.max(out, 1)

array([0.6, 0.7])

In [144]:
np.all((out > 0.5) == label, axis=1)

array([ True, False])